name: build

on:
  push:
    branches: [main]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-release:
    name: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targets:
          - os: 'darwin'
            arch: 'amd64'
            cross: false
          - os: 'linux'
            arch: 'amd64'
            cross: false
          - os: 'windows'
            arch: 'amd64'
            cross: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20'
          check-latest: true
          cache-dependency-path: subdir/go.sum
      - name: Build for ${{ matrix.targets.os }} / ${{ matrix.targets.arch }}
        run: GOOS="${{ matrix.targets.os }}" GOARCH="${{ matrix.targets.arch }}" go build